services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network
    ports:
      - "3308:3306"

  app:
    image: 'bitnami/laravel:11' # Updated to Laravel version 11
    container_name: laravel
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mysql # Updated to match the MySQL service name
      - DB_PORT=3306  # Ensure it matches the container's internal port
      - DB_DATABASE=laravel_db # Matches the database name in the MySQL service
      - DB_USERNAME=laravel     # Matches the username in the MySQL service
      - DB_PASSWORD=secret      # Matches the password in the MySQL service
      - BITNAMI_APP_USER=1000
      - BITNAMI_APP_GROUP=1000
    volumes:
      - ./src:/app
    networks:
      - laravel_network
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local

networks:
  laravel_network:
    driver: bridge