version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: ${UID}
        uid: ${UID}
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    user: "${UID}:${GID}"
    environment:
      - DOCKER_USER=${UID}
    volumes:
      - ./src:/var/www:cached
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:cached
    networks:
      - laravel
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql:cached
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
    name: laravel-network

volumes:
  mysql-data:
    driver: local