version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysqlapigeneradordata # Cambiado aquí
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
      TZ: ${TZ}
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    user: "${MY_UID}:${MY_GID}"
    networks:
      - laravel

  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MY_UID: ${MY_UID}
      MY_GID: ${MY_GID}
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel
    user: "${MY_UID}:${MY_GID}"

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
