services:
  mysql:
    image: mysql:8.0
    container_name: mysql_apigeneradordata
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Madrid
    ports:
      - "3311:3306"
    volumes:
      - db_data_apigeneradordata:/var/lib/mysql
    networks:
      - apigeneradordata_net

  app:
    build: .
    container_name: app_apigeneradordata
    restart: unless-stopped
    environment:
      APP_ENV: local
      APP_KEY: base64:45htVXDiQi9Dg6MtTd+MiUlVoko01W0jyFtApyI2gNs=
      APP_DEBUG: true
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      TZ: Europe/Madrid
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    ports:
      - "8001:8000"
    networks:
      - apigeneradordata_net

volumes:
  db_data_apigeneradordata:

networks:
  apigeneradordata_net:
    driver: bridge
